"""empty message

Revision ID: ed555e601296
Revises: 88d4b18eb587
Create Date: 2021-04-18 22:37:03.827705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed555e601296'
down_revision = '88d4b18eb587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Favourites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Favourites',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Favourites_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Favourites_pkey')
    )
    op.drop_table('favourites')
    # ### end Alembic commands ###
